# -*- coding: utf-8 -*-
"""detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pOLkeH2f5AuPv2YSOGlXvDC1s_skkhT0
"""

pip install detecto

import detecto
from detecto import utils, visualize
from detecto.core import Model
import numpy as np

dataset = core.Dataset('/content/drive/MyDrive/Deep Learning/all')

model = core.Model(['command', 'crosswalk', 'no_entry', 'speed_limit', 'warning'])
model.fit(dataset)
model.save('detaction.pth')

model.save('/content/drive/MyDrive/4th/Deep Learning/Project/Deep Learning/model/detaction.pth')

model = detecto.core.Model.load('/content/drive/MyDrive/4th/Deep Learning/Project/Deep Learning/model/detaction.pth', ['command', 'crosswalk', 'no_entry', 'speed_limit', 'warning'])

def detection(image):
    labels, boxes, scores = model.predict(image)
    predictions = model.predict_top(image)

    filter_all = np.where(scores > 0.9)
    filter_boxes = boxes[filter_all]

    detecto.visualize.show_labeled_image(image, filter_boxes)

image = detecto.utils.read_image('/content/drive/MyDrive/4th/Deep Learning/Project/Deep Learning/traffic_Data/test/crosswalk/crosswalk (11).jpg')

detection(image)

image = detecto.utils.read_image('/content/drive/MyDrive/4th/Deep Learning/Project/Deep Learning/traffic_Data/test/command/command (3).jpg')

detection(image)

